name: Deploy Laravel API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login no DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construir e enviar imagem para Docker Hub
      run: |
        docker build -t meu_usuario/laravel_api .
        docker tag meu_usuario/laravel_api meu_usuario/laravel_api:latest
        docker push meu_usuario/laravel_api:latest

    - name: Conectar e atualizar container na AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
        docker pull meu_usuario/laravel_api:latest
        docker stop laravel_app || true
        docker rm laravel_app || true
        docker run -d --name laravel_app -p 80:80 --env-file .env meu_usuario/laravel_api:latest
        EOF
